service: code

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  customDomain:
    domainName: code.wdsm.io
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256
  timeout: 5
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    SLS_STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
      Effect: Allow

functions:
  main:
    handler: server/index.handler
    events:
      - http:
          path: /
          method: get
  features:
    handler: server/features.handler
    events:
      - http:
          path: /features
          method: get
  create:
    handler: server/create.create
    events:
      - http:
          path: /
          method: post
          cors: true
  login:
    handler: server/login.login
    events:
      - http:
          path: /login
          method: get
          cors: true
  userCode:
    handler: server/code.list
    events:
      - http:
          path: user/{userId}
          method: get
  code:
    handler: server/code.detail
    events:
      - http:
          path: code/{codeId}
          method: get
  updateCode:
    handler: server/code.update
    events:
      - http:
          path: code/{codeId}
          method: post

resources:
  Resources:
    LinkDB:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
